# Authentication Settings and Session Management
# Memo AI Coach - Authentication Configuration

session_management:
  session_timeout: 3600
  session_cleanup_interval: 300
  max_sessions_per_user: 5
  max_concurrent_users: 100
  log_level: "INFO"
  session_warning_threshold: 10  # minutes
  session_refresh_interval: 60   # seconds
  session_token_length: 32
  session_token_alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
  secure_cookies: true
  http_only_cookies: true
  same_site_policy: "lax"

authentication_methods:
  session_based:
    enabled: true
    primary_method: true
    anonymous_sessions: true
    session_validation: true
    # High Priority: Add session rotation on privilege escalation
    rotate_session_on_admin_login: true
    
  admin_authentication:
    enabled: true
    username_field: "username"
    password_field: "password"
    bcrypt_rounds: 12
    max_login_attempts: 5
    lockout_duration: 900
    password_min_length: 8
    password_complexity: true
    # High Priority: Add brute force detection
    brute_force_detection: true
    brute_force_threshold: 3
    brute_force_window: 300

security_settings:
  csrf_protection:
    enabled: true
    token_length: 32
    token_expiry: 3600
    header_name: "X-CSRF-Token"
    
  rate_limiting:
    enabled: true
    requests_per_session_per_hour: 20
    requests_per_admin_per_hour: 100
    global_requests_per_hour: 1000
    rate_limit_window: 3600
    
  input_validation:
    max_username_length: 50
    min_username_length: 3
    username_allowed_chars: "a-zA-Z0-9_-"
    max_password_length: 128
    min_password_length: 8
    password_requirements:
      - "At least one uppercase letter"
      - "At least one lowercase letter"
      - "At least one digit"
      - "At least one special character"
      
  data_protection:
    encrypt_sensitive_data: true
    hash_passwords: true
    salt_rounds: 12
    session_data_encryption: true
    audit_logging: true
    # High Priority: Add session integrity validation
    validate_session_integrity: true
    # High Priority: Add encryption key rotation
    encryption_key_rotation_days: 90
    # High Priority: Add secure session storage validation
    secure_session_storage: true

admin_credentials:
  default_admin:
    username: "admin"
    password_hash: "${ADMIN_PASSWORD_HASH}"
    is_admin: true
    is_active: true
    created_at: "2024-01-01T00:00:00Z"
    
  admin_roles:
    super_admin:
      permissions:
        - "system_configuration"
        - "user_management"
        - "debug_access"
        - "backup_management"
        - "log_access"
        
    admin:
      permissions:
        - "configuration_management"
        - "debug_access"
        - "log_access"

session_storage:
  database_storage:
    enabled: true
    table_name: "sessions"
    cleanup_enabled: true
    cleanup_interval: 300
    # High Priority: Add connection pooling for 100+ user support
    connection_pool_size: 10
    connection_pool_timeout: 30
    # High Priority: Add performance monitoring
    performance_monitoring: true
    
  memory_storage:
    enabled: false
    max_sessions: 1000
    cleanup_enabled: true
    
  redis_storage:
    enabled: false
    redis_url: "redis://localhost:6379"
    key_prefix: "memoai:session:"
    expiry_handling: "redis"

user_management:
  user_registration:
    enabled: false
    require_email_verification: false
    require_admin_approval: false
    
  user_profiles:
    enabled: false
    profile_fields:
      - "username"
      - "email"
      - "created_at"
      - "last_login"
      
  password_policy:
    min_length: 8
    max_length: 128
    require_uppercase: true
    require_lowercase: true
    require_digits: true
    require_special_chars: true
    prevent_common_passwords: true
    password_history: 5

  audit_logging:
    enabled: true
    log_events:
      - "login_success"
      - "login_failure"
      - "logout"
      - "session_creation"
      - "session_expiry"
      - "admin_action"
      - "configuration_change"
      - "security_event"
      # High Priority: Add security monitoring events
      - "session_hijacking_detected"
      - "brute_force_detected"
      - "privilege_escalation_attempt"
      - "audit_log_failure"
      
    log_retention:
      retention_days: 90
      archive_enabled: true
      archive_compression: true
      # High Priority: Add log integrity protection
      log_integrity_checks: true
      # High Priority: Add sensitive data masking
      mask_sensitive_data: true

error_handling:
  authentication_errors:
    invalid_credentials: "Invalid username or password"
    account_locked: "Account temporarily locked due to multiple failed attempts"
    session_expired: "Session has expired. Please log in again"
    insufficient_permissions: "Insufficient permissions for this action"
    
  validation_errors:
    username_invalid: "Username must be 3-50 characters and contain only letters, numbers, underscores, and hyphens"
    password_weak: "Password does not meet security requirements"
    session_invalid: "Invalid session token"
    
  rate_limit_errors:
    session_rate_limited: "Too many requests from this session. Please try again later"
    admin_rate_limited: "Too many admin operations. Please try again later"
    global_rate_limited: "Service temporarily unavailable due to high traffic"
    
  # High Priority: Add security-specific error handling
  security_errors:
    session_hijacking_detected: "Suspicious session activity detected. Please log in again"
    brute_force_detected: "Multiple failed login attempts detected. Account temporarily locked"
    privilege_escalation_attempt: "Unauthorized privilege escalation attempt detected"
    session_integrity_failure: "Session integrity validation failed. Please log in again"
    
  # High Priority: Add compliance error handling
  compliance_errors:
    audit_log_failure: "Failed to log security event. Please contact administrator"
    data_retention_violation: "Data retention policy violation detected"
    encryption_key_expired: "Security key expired. Please contact administrator"

# High Priority: Add security monitoring and validation section
security_monitoring:
  session_monitoring:
    enabled: true
    detect_session_hijacking: true
    detect_privilege_escalation: true
    validate_session_integrity: true
    session_anomaly_threshold: 0.8
    
  threat_detection:
    enabled: true
    brute_force_detection: true
    suspicious_ip_detection: true
    unusual_activity_detection: true
    threat_score_threshold: 0.7
    
  validation_rules:
    # High Priority: Add explicit validation field requirements
    session_timeout_range: [300, 86400]  # 5 minutes to 24 hours
    session_cleanup_interval_range: [60, 3600]  # 1 minute to 1 hour
    max_sessions_per_user_range: [1, 20]
    max_login_attempts_range: [3, 10]
    min_password_length_range: [8, 128]
    max_username_length_range: [3, 50]

environment_specific:
  development:
    debug_mode: true
    session_timeout: 7200
    rate_limiting: false
    secure_cookies: false
    audit_logging: true
    
  production:
    debug_mode: false
    session_timeout: 3600
    rate_limiting: true
    secure_cookies: true
    audit_logging: true
    csrf_protection: true
    input_validation: true
