# DEPRECATED: This file is no longer used. All rubric content has been moved to prompt.yaml
# The new rubric structure uses 4 criteria with weights totaling 100%
# See prompt.yaml for the current rubric configuration
#
# DEPRECATED SECTIONS REMOVED:
# - frameworks section
# - evaluation_framework section  
# - segment_evaluation section
# - All rubric criteria (moved to prompt.yaml)
#
# NEW STRUCTURE IN prompt.yaml:
# - context/request/rubric structure for each language
# - 4 core criteria: structure, arguments_and_evidence, strategic_alignment, implementation_and_risks
# - Weights: 25%, 30%, 25%, 20% (total = 100%)
# - Scoring range: 1-5 scale
# - Full English and Spanish support
#
# This file will be completely removed in a future version.
# Update your configuration to use prompt.yaml instead.

# Minimal YAML content to prevent validation errors
status: "deprecated"
message: "This file is no longer used. All rubric content has been moved to prompt.yaml"
deprecation_date: "2024-09-02"
replacement_file: "prompt.yaml"
